/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.server.form;

import rs.stefanlezaic.zeleznice.srbije.lib.domen.Linija;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.MedjuStanica;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Mesto;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Polazak;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Stanica;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.TipLinije;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Voz;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import rs.stefanlezaic.zeleznice.srbije.server.kontroler.Kontroler;
import rs.stefanlezaic.zeleznice.srbije.server.modeli.tabela.ModelTabeleMedjustanica;
import rs.stefanlezaic.zeleznice.srbije.server.modeli.tabela.ModelTabelePolaska;
import rs.stefanlezaic.zeleznice.srbije.server.niti.PokreniServerNit;
import rs.stefanlezaic.zeleznice.srbije.lib.sat.Sat;
import rs.stefanlezaic.zeleznice.srbije.lib.kalendar.Kalendar;
import rs.stefanlezaic.zeleznice.srbije.lib.swing.Tabela;
import rs.stefanlezaic.zeleznice.srbije.lib.theme.Tema;

/**
 *
 * @author sleza
 */
public class FormaLinija extends javax.swing.JFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
    ModelTabeleMedjustanica mtms = new ModelTabeleMedjustanica();
    ModelTabelePolaska mtp = new ModelTabelePolaska();
    ModelTabelePolaska mtsp = new ModelTabelePolaska();
    Sat sat;
    Tema tema;
    Kalendar kalendar;
    Tabela tabela;

    /**
     * Creates new form FormaLinija
     */
    public FormaLinija() {
        initComponents();
        centrirajFrame();
        tema = new Tema(this);
        tabela = new Tabela(this);
        kalendar = new Kalendar(cmbDani, cmbMeseci, cmbGodina);
        kalendar.srediDaneMeseceGodinu();
        sat = new Sat(lblSat);
        ukljuciDarkMode();
        pokreniServer();
        ucitajSveIzBaze();
        urediTabeluPolazaka();
        urediTabeluSviPolasci();
        urediTabeluMedjuStanica();
        pokreniPanelLinije();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSat = new javax.swing.JLabel();
        panelLinija = new javax.swing.JPanel();
        lblNazivFrejma = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        btnObrisiMedjustanicu = new javax.swing.JButton();
        cmbLinije = new javax.swing.JComboBox();
        btnDodajMedjustanicu = new javax.swing.JButton();
        lblNaziv = new javax.swing.JLabel();
        cmbMedjustanica = new javax.swing.JComboBox();
        lblTip = new javax.swing.JLabel();
        txtKilometraza = new javax.swing.JTextField();
        lblNaziv2 = new javax.swing.JLabel();
        btnIzmeniRedosledMedjustanica = new javax.swing.JButton();
        lblNazivLinijeKodTabele = new javax.swing.JLabel();
        txtMinutaza = new javax.swing.JTextField();
        lblNazivLinije = new javax.swing.JLabel();
        lblKranja = new javax.swing.JLabel();
        btnUnesiLiniju = new javax.swing.JButton();
        lblKm = new javax.swing.JLabel();
        lblpocetna = new javax.swing.JLabel();
        cmbPocetna = new javax.swing.JComboBox();
        cmbKrajnja = new javax.swing.JComboBox();
        lblNaziv3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMedjustanica = new javax.swing.JTable();
        cmbTip = new javax.swing.JComboBox();
        btnObrisiLiniju = new javax.swing.JButton();
        btnUnesiStanicu = new javax.swing.JButton();
        cmbMestaZaStanice = new javax.swing.JComboBox();
        lblKm1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNazivStanice = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblNazivFrejma1 = new javax.swing.JLabel();
        lblNazivFrejma2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblDarkMode = new javax.swing.JLabel();
        lblWhiteMode = new javax.swing.JLabel();
        panelPolazak = new javax.swing.JPanel();
        lblNaziv4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPolazaka = new javax.swing.JTable();
        lblDatum = new javax.swing.JLabel();
        lblVoz = new javax.swing.JLabel();
        lblpocetna1 = new javax.swing.JLabel();
        lblDatumDolaska = new javax.swing.JLabel();
        cmbVoz = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblDatum1 = new javax.swing.JLabel();
        spinerMinuti = new javax.swing.JSpinner();
        cmbDani = new javax.swing.JComboBox();
        lblNazivPolaska = new javax.swing.JLabel();
        cmbMeseci = new javax.swing.JComboBox<>();
        cmbLinijaPolazak = new javax.swing.JComboBox();
        cmbGodina = new javax.swing.JComboBox();
        lblListaPolazaka = new javax.swing.JLabel();
        btnDodajPolazak = new javax.swing.JButton();
        btnZapamtiPolaske = new javax.swing.JButton();
        btnLinija = new javax.swing.JLabel();
        btnObrisiPolazak = new javax.swing.JButton();
        spinerSati = new javax.swing.JSpinner();
        cmbBrojDanaZaPolazak = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cboxPovratna = new javax.swing.JCheckBox();
        btnObrisiListu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        panelSviPolasci = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSviPolasci = new javax.swing.JTable();
        btnObrisiPolazakIzTabeleSviPolasci = new javax.swing.JButton();
        btnUpdejtuj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbSortiraj = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MeniLinijia = new javax.swing.JMenu();
        MeniPolazak = new javax.swing.JMenu();
        MeniSviPolasci = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ZELEZNICE SRBIJE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1336, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        lblSat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSat.setForeground(new java.awt.Color(255, 255, 255));
        lblSat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_schedule_32px.png"))); // NOI18N
        lblSat.setToolTipText("");
        getContentPane().add(lblSat);
        lblSat.setBounds(930, 0, 360, 30);

        panelLinija.setBackground(new java.awt.Color(44, 44, 44));
        panelLinija.setForeground(new java.awt.Color(0, 0, 0));
        panelLinija.setMinimumSize(new java.awt.Dimension(1550, 1000));
        panelLinija.setPreferredSize(new java.awt.Dimension(1550, 1000));
        panelLinija.setLayout(null);

        lblNazivFrejma.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNazivFrejma.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivFrejma.setText("Unos medjustanica");
        panelLinija.add(lblNazivFrejma);
        lblNazivFrejma.setBounds(520, 5, 350, 40);

        lblMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_stopwatch_32px.png"))); // NOI18N
        lblMin.setText("Minutaza:");
        panelLinija.add(lblMin);
        lblMin.setBounds(15, 220, 140, 30);

        btnObrisiMedjustanicu.setBackground(new java.awt.Color(153, 153, 153));
        btnObrisiMedjustanicu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnObrisiMedjustanicu.setForeground(new java.awt.Color(0, 0, 0));
        btnObrisiMedjustanicu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_minus_64px.png"))); // NOI18N
        btnObrisiMedjustanicu.setText("Obrisi");
        btnObrisiMedjustanicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiMedjustanicuActionPerformed(evt);
            }
        });
        panelLinija.add(btnObrisiMedjustanicu);
        btnObrisiMedjustanicu.setBounds(740, 140, 190, 40);

        cmbLinije.setBackground(new java.awt.Color(153, 153, 153));
        cmbLinije.setForeground(new java.awt.Color(0, 0, 0));
        cmbLinije.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLinije.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLinijeItemStateChanged(evt);
            }
        });
        panelLinija.add(cmbLinije);
        cmbLinije.setBounds(590, 60, 530, 30);

        btnDodajMedjustanicu.setBackground(new java.awt.Color(153, 153, 153));
        btnDodajMedjustanicu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDodajMedjustanicu.setForeground(new java.awt.Color(0, 0, 0));
        btnDodajMedjustanicu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_plus_64px.png"))); // NOI18N
        btnDodajMedjustanicu.setText("Dodaj ");
        btnDodajMedjustanicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMedjustanicuActionPerformed(evt);
            }
        });
        panelLinija.add(btnDodajMedjustanicu);
        btnDodajMedjustanicu.setBounds(940, 140, 180, 40);

        lblNaziv.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_itinerary_32px.png"))); // NOI18N
        lblNaziv.setText("Naziv:");
        panelLinija.add(lblNaziv);
        lblNaziv.setBounds(15, 260, 140, 30);

        cmbMedjustanica.setBackground(new java.awt.Color(153, 153, 153));
        cmbMedjustanica.setForeground(new java.awt.Color(0, 0, 0));
        cmbMedjustanica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelLinija.add(cmbMedjustanica);
        cmbMedjustanica.setBounds(770, 100, 350, 30);

        lblTip.setForeground(new java.awt.Color(255, 255, 255));
        lblTip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_city_railway_station_32px.png"))); // NOI18N
        lblTip.setText("Tip linije:");
        lblTip.setPreferredSize(new java.awt.Dimension(50, 15));
        lblTip.setRequestFocusEnabled(false);
        panelLinija.add(lblTip);
        lblTip.setBounds(15, 140, 140, 30);

        txtKilometraza.setBackground(new java.awt.Color(102, 102, 102));
        txtKilometraza.setForeground(new java.awt.Color(0, 0, 0));
        panelLinija.add(txtKilometraza);
        txtKilometraza.setBounds(170, 180, 120, 30);

        lblNaziv2.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_flag_filled_32px.png"))); // NOI18N
        lblNaziv2.setText("Medjustanica:");
        panelLinija.add(lblNaziv2);
        lblNaziv2.setBounds(630, 100, 130, 30);

        btnIzmeniRedosledMedjustanica.setBackground(new java.awt.Color(153, 153, 153));
        btnIzmeniRedosledMedjustanica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIzmeniRedosledMedjustanica.setForeground(new java.awt.Color(0, 0, 0));
        btnIzmeniRedosledMedjustanica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_save_64px.png"))); // NOI18N
        btnIzmeniRedosledMedjustanica.setText("Izmeni redosled");
        btnIzmeniRedosledMedjustanica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniRedosledMedjustanicaActionPerformed(evt);
            }
        });
        panelLinija.add(btnIzmeniRedosledMedjustanica);
        btnIzmeniRedosledMedjustanica.setBounds(810, 550, 310, 50);

        lblNazivLinijeKodTabele.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNazivLinijeKodTabele.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivLinijeKodTabele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_list_32px.png"))); // NOI18N
        lblNazivLinijeKodTabele.setText("Lista stanica:");
        panelLinija.add(lblNazivLinijeKodTabele);
        lblNazivLinijeKodTabele.setBounds(520, 140, 210, 40);

        txtMinutaza.setBackground(new java.awt.Color(102, 102, 102));
        txtMinutaza.setForeground(new java.awt.Color(0, 0, 0));
        panelLinija.add(txtMinutaza);
        txtMinutaza.setBounds(170, 220, 120, 30);

        lblNazivLinije.setForeground(new java.awt.Color(255, 255, 255));
        panelLinija.add(lblNazivLinije);
        lblNazivLinije.setBounds(170, 260, 300, 30);

        lblKranja.setForeground(new java.awt.Color(255, 255, 255));
        lblKranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_marker_32px.png"))); // NOI18N
        lblKranja.setText("Krajnja stanica:");
        panelLinija.add(lblKranja);
        lblKranja.setBounds(15, 100, 140, 30);

        btnUnesiLiniju.setBackground(new java.awt.Color(153, 153, 153));
        btnUnesiLiniju.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUnesiLiniju.setForeground(new java.awt.Color(0, 0, 0));
        btnUnesiLiniju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_add_64px_2.png"))); // NOI18N
        btnUnesiLiniju.setText("Unesi liniju");
        btnUnesiLiniju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiLinijuActionPerformed(evt);
            }
        });
        panelLinija.add(btnUnesiLiniju);
        btnUnesiLiniju.setBounds(170, 300, 300, 40);

        lblKm.setForeground(new java.awt.Color(255, 255, 255));
        lblKm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_length_32px_1.png"))); // NOI18N
        lblKm.setText("Kilometraza:");
        panelLinija.add(lblKm);
        lblKm.setBounds(15, 180, 140, 30);

        lblpocetna.setForeground(new java.awt.Color(255, 255, 255));
        lblpocetna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_marker_32px.png"))); // NOI18N
        lblpocetna.setText("Pocetna stanica:");
        panelLinija.add(lblpocetna);
        lblpocetna.setBounds(15, 60, 140, 30);

        cmbPocetna.setBackground(new java.awt.Color(102, 102, 102));
        cmbPocetna.setForeground(new java.awt.Color(0, 0, 0));
        cmbPocetna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelLinija.add(cmbPocetna);
        cmbPocetna.setBounds(170, 60, 300, 30);

        cmbKrajnja.setBackground(new java.awt.Color(153, 153, 153));
        cmbKrajnja.setForeground(new java.awt.Color(0, 0, 0));
        cmbKrajnja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelLinija.add(cmbKrajnja);
        cmbKrajnja.setBounds(170, 100, 300, 30);

        lblNaziv3.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_tracks_32px.png"))); // NOI18N
        lblNaziv3.setText("Linija:");
        panelLinija.add(lblNaziv3);
        lblNaziv3.setBounds(510, 60, 70, 30);

        jScrollPane1.setBackground(new java.awt.Color(187, 187, 187));

        tabelaMedjustanica.setBackground(new java.awt.Color(153, 153, 153));
        tabelaMedjustanica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaMedjustanica.setFocusable(false);
        tabelaMedjustanica.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaMedjustanica.setRowHeight(25);
        jScrollPane1.setViewportView(tabelaMedjustanica);

        panelLinija.add(jScrollPane1);
        jScrollPane1.setBounds(520, 190, 600, 290);

        cmbTip.setBackground(new java.awt.Color(153, 153, 153));
        cmbTip.setForeground(new java.awt.Color(0, 0, 0));
        cmbTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelLinija.add(cmbTip);
        cmbTip.setBounds(170, 140, 300, 30);

        btnObrisiLiniju.setBackground(new java.awt.Color(153, 153, 153));
        btnObrisiLiniju.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnObrisiLiniju.setForeground(new java.awt.Color(0, 0, 0));
        btnObrisiLiniju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_delete_64px.png"))); // NOI18N
        btnObrisiLiniju.setText("OBRISI LINIJU");
        btnObrisiLiniju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiLinijuActionPerformed(evt);
            }
        });
        panelLinija.add(btnObrisiLiniju);
        btnObrisiLiniju.setBounds(520, 550, 280, 50);

        btnUnesiStanicu.setBackground(new java.awt.Color(153, 153, 153));
        btnUnesiStanicu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUnesiStanicu.setForeground(new java.awt.Color(0, 0, 0));
        btnUnesiStanicu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_add_64px_2.png"))); // NOI18N
        btnUnesiStanicu.setText("Unesi stanicu");
        btnUnesiStanicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiStanicuActionPerformed(evt);
            }
        });
        panelLinija.add(btnUnesiStanicu);
        btnUnesiStanicu.setBounds(170, 500, 300, 40);

        cmbMestaZaStanice.setBackground(new java.awt.Color(153, 153, 153));
        cmbMestaZaStanice.setForeground(new java.awt.Color(0, 0, 0));
        cmbMestaZaStanice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelLinija.add(cmbMestaZaStanice);
        cmbMestaZaStanice.setBounds(170, 460, 300, 30);

        lblKm1.setForeground(new java.awt.Color(255, 255, 255));
        lblKm1.setText("Mesto:");
        panelLinija.add(lblKm1);
        lblKm1.setBounds(15, 460, 140, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Naziv stanice:");
        panelLinija.add(jLabel3);
        jLabel3.setBounds(15, 420, 140, 30);

        txtNazivStanice.setBackground(new java.awt.Color(102, 102, 102));
        txtNazivStanice.setForeground(new java.awt.Color(0, 0, 0));
        panelLinija.add(txtNazivStanice);
        txtNazivStanice.setBounds(170, 420, 300, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelLinija.add(jSeparator2);
        jSeparator2.setBounds(485, 0, 40, 700);

        lblNazivFrejma1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNazivFrejma1.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivFrejma1.setText("Unos linije voza");
        panelLinija.add(lblNazivFrejma1);
        lblNazivFrejma1.setBounds(15, 5, 300, 40);

        lblNazivFrejma2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNazivFrejma2.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivFrejma2.setText("Unos stanice");
        panelLinija.add(lblNazivFrejma2);
        lblNazivFrejma2.setBounds(15, 360, 300, 40);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelLinija.add(jSeparator3);
        jSeparator3.setBounds(170, 290, 300, 10);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Km");
        panelLinija.add(jLabel6);
        jLabel6.setBounds(300, 180, 30, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Min");
        panelLinija.add(jLabel7);
        jLabel7.setBounds(300, 220, 30, 30);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelLinija.add(jSeparator5);
        jSeparator5.setBounds(15, 345, 470, 10);

        lblDarkMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDarkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/darkMode.png"))); // NOI18N
        lblDarkMode.setText("Dark theme");
        lblDarkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDarkModeMouseClicked(evt);
            }
        });
        panelLinija.add(lblDarkMode);
        lblDarkMode.setBounds(1131, 50, 190, 50);

        lblWhiteMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWhiteMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/whiteMode.png"))); // NOI18N
        lblWhiteMode.setText("White theme");
        lblWhiteMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhiteModeMouseClicked(evt);
            }
        });
        panelLinija.add(lblWhiteMode);
        lblWhiteMode.setBounds(1131, 50, 190, 50);

        getContentPane().add(panelLinija);
        panelLinija.setBounds(0, 0, 1336, 768);

        panelPolazak.setBackground(new java.awt.Color(44, 44, 44));
        panelPolazak.setForeground(new java.awt.Color(255, 255, 255));
        panelPolazak.setMinimumSize(new java.awt.Dimension(1550, 1000));
        panelPolazak.setName(""); // NOI18N
        panelPolazak.setPreferredSize(new java.awt.Dimension(1550, 1000));
        panelPolazak.setLayout(null);

        lblNaziv4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNaziv4.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_itinerary_32px.png"))); // NOI18N
        lblNaziv4.setText("Naziv:");
        panelPolazak.add(lblNaziv4);
        lblNaziv4.setBounds(15, 190, 150, 30);

        tabelaPolazaka.setBackground(new java.awt.Color(153, 153, 153));
        tabelaPolazaka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPolazaka.setFocusable(false);
        tabelaPolazaka.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaPolazaka.setRowHeight(25);
        tabelaPolazaka.getTableHeader().setResizingAllowed(false);
        tabelaPolazaka.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaPolazaka);

        panelPolazak.add(jScrollPane2);
        jScrollPane2.setBounds(10, 340, 1160, 190);

        lblDatum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDatum.setForeground(new java.awt.Color(255, 255, 255));
        lblDatum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_schedule_32px.png"))); // NOI18N
        lblDatum.setText("Datum polaska:");
        panelPolazak.add(lblDatum);
        lblDatum.setBounds(15, 110, 150, 30);

        lblVoz.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVoz.setForeground(new java.awt.Color(255, 255, 255));
        lblVoz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_train_32px.png"))); // NOI18N
        lblVoz.setText("Voz:");
        panelPolazak.add(lblVoz);
        lblVoz.setBounds(15, 230, 150, 30);

        lblpocetna1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblpocetna1.setForeground(new java.awt.Color(255, 255, 255));
        lblpocetna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_tracks_32px.png"))); // NOI18N
        lblpocetna1.setText("Linija:");
        panelPolazak.add(lblpocetna1);
        lblpocetna1.setBounds(15, 70, 150, 30);

        lblDatumDolaska.setForeground(new java.awt.Color(255, 255, 255));
        panelPolazak.add(lblDatumDolaska);
        lblDatumDolaska.setBounds(170, 150, 100, 30);

        cmbVoz.setBackground(new java.awt.Color(153, 153, 153));
        cmbVoz.setForeground(new java.awt.Color(0, 0, 0));
        cmbVoz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelPolazak.add(cmbVoz);
        cmbVoz.setBounds(170, 230, 140, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_sand_watch_32px.png"))); // NOI18N
        jLabel2.setText("Vreme:");
        panelPolazak.add(jLabel2);
        jLabel2.setBounds(450, 110, 90, 30);

        lblDatum1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDatum1.setForeground(new java.awt.Color(255, 255, 255));
        lblDatum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_schedule_32px.png"))); // NOI18N
        lblDatum1.setText("Datum dolaska: ");
        panelPolazak.add(lblDatum1);
        lblDatum1.setBounds(15, 150, 150, 30);

        spinerMinuti.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spinerMinuti.setToolTipText("");
        spinerMinuti.setBorder(null);
        spinerMinuti.setFocusable(false);
        spinerMinuti.setOpaque(false);
        panelPolazak.add(spinerMinuti);
        spinerMinuti.setBounds(630, 110, 70, 30);
        spinerMinuti.setBackground(new Color(112, 122, 122));
        spinerMinuti.setForeground(Color.BLACK);

        cmbDani.setBackground(new java.awt.Color(153, 153, 153));
        cmbDani.setForeground(new java.awt.Color(0, 0, 0));
        cmbDani.setOpaque(false);
        panelPolazak.add(cmbDani);
        cmbDani.setBounds(170, 110, 70, 30);

        lblNazivPolaska.setForeground(new java.awt.Color(255, 255, 255));
        panelPolazak.add(lblNazivPolaska);
        lblNazivPolaska.setBounds(170, 190, 840, 30);

        cmbMeseci.setBackground(new java.awt.Color(153, 153, 153));
        cmbMeseci.setForeground(new java.awt.Color(0, 0, 0));
        cmbMeseci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "Mart", "April", "Maj", "Jun", "Jul", "Avgust", "Septembar", "Oktobar", "Novembar", "Decembar" }));
        cmbMeseci.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMeseciItemStateChanged(evt);
            }
        });
        panelPolazak.add(cmbMeseci);
        cmbMeseci.setBounds(250, 110, 100, 30);

        cmbLinijaPolazak.setBackground(new java.awt.Color(153, 153, 153));
        cmbLinijaPolazak.setForeground(new java.awt.Color(0, 0, 0));
        cmbLinijaPolazak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLinijaPolazak.setSelectedIndex(-1);
        cmbLinijaPolazak.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLinijaPolazakItemStateChanged(evt);
            }
        });
        panelPolazak.add(cmbLinijaPolazak);
        cmbLinijaPolazak.setBounds(170, 70, 640, 30);

        cmbGodina.setBackground(new java.awt.Color(153, 153, 153));
        cmbGodina.setForeground(new java.awt.Color(0, 0, 0));
        cmbGodina.setOpaque(false);
        cmbGodina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGodinaItemStateChanged(evt);
            }
        });
        panelPolazak.add(cmbGodina);
        cmbGodina.setBounds(360, 110, 80, 30);

        lblListaPolazaka.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblListaPolazaka.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPolazaka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_list_32px.png"))); // NOI18N
        lblListaPolazaka.setText("Lista polazaka:");
        panelPolazak.add(lblListaPolazaka);
        lblListaPolazaka.setBounds(15, 290, 220, 40);

        btnDodajPolazak.setBackground(new java.awt.Color(153, 153, 153));
        btnDodajPolazak.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDodajPolazak.setForeground(new java.awt.Color(0, 0, 0));
        btnDodajPolazak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_plus_64px.png"))); // NOI18N
        btnDodajPolazak.setText("Dodaj polazak");
        btnDodajPolazak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPolazakActionPerformed(evt);
            }
        });
        panelPolazak.add(btnDodajPolazak);
        btnDodajPolazak.setBounds(870, 290, 300, 45);

        btnZapamtiPolaske.setBackground(new java.awt.Color(153, 153, 153));
        btnZapamtiPolaske.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnZapamtiPolaske.setForeground(new java.awt.Color(0, 0, 0));
        btnZapamtiPolaske.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_save_64px.png"))); // NOI18N
        btnZapamtiPolaske.setText("Zapamti polaske");
        btnZapamtiPolaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiPolaskeActionPerformed(evt);
            }
        });
        panelPolazak.add(btnZapamtiPolaske);
        btnZapamtiPolaske.setBounds(870, 540, 300, 45);

        btnLinija.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnLinija.setForeground(new java.awt.Color(255, 255, 255));
        btnLinija.setText("Unos polazaka putnickog voza");
        panelPolazak.add(btnLinija);
        btnLinija.setBounds(15, 10, 530, 50);

        btnObrisiPolazak.setBackground(new java.awt.Color(153, 153, 153));
        btnObrisiPolazak.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnObrisiPolazak.setForeground(new java.awt.Color(0, 0, 0));
        btnObrisiPolazak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_minus_64px.png"))); // NOI18N
        btnObrisiPolazak.setText("Izbaci polazak");
        btnObrisiPolazak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPolazakActionPerformed(evt);
            }
        });
        panelPolazak.add(btnObrisiPolazak);
        btnObrisiPolazak.setBounds(560, 290, 300, 45);

        spinerSati.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        spinerSati.setFocusable(false);
        spinerSati.setOpaque(false);
        panelPolazak.add(spinerSati);
        spinerSati.setBounds(550, 110, 70, 30);

        cmbBrojDanaZaPolazak.setBackground(new java.awt.Color(153, 153, 153));
        cmbBrojDanaZaPolazak.setForeground(new java.awt.Color(0, 0, 0));
        cmbBrojDanaZaPolazak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 dan", "7 dana", "10 dana", "15 dana" }));
        panelPolazak.add(cmbBrojDanaZaPolazak);
        cmbBrojDanaZaPolazak.setBounds(800, 110, 100, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Za narednih:");
        panelPolazak.add(jLabel1);
        jLabel1.setBounds(710, 110, 80, 30);

        cboxPovratna.setBackground(new java.awt.Color(102, 102, 102));
        cboxPovratna.setForeground(new java.awt.Color(255, 255, 255));
        cboxPovratna.setText("Povratna?");
        panelPolazak.add(cboxPovratna);
        cboxPovratna.setBounds(910, 110, 90, 30);

        btnObrisiListu.setBackground(new java.awt.Color(153, 153, 153));
        btnObrisiListu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnObrisiListu.setForeground(new java.awt.Color(0, 0, 0));
        btnObrisiListu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_trash_can_64px.png"))); // NOI18N
        btnObrisiListu.setText("Obrisi listu");
        btnObrisiListu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiListuActionPerformed(evt);
            }
        });
        panelPolazak.add(btnObrisiListu);
        btnObrisiListu.setBounds(15, 540, 300, 45);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        panelPolazak.add(jSeparator1);
        jSeparator1.setBounds(170, 220, 700, 10);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        panelPolazak.add(jSeparator4);
        jSeparator4.setBounds(170, 180, 100, 10);

        getContentPane().add(panelPolazak);
        panelPolazak.setBounds(0, 0, 1336, 768);

        panelSviPolasci.setBackground(new java.awt.Color(44, 44, 44));
        panelSviPolasci.setForeground(new java.awt.Color(0, 0, 0));
        panelSviPolasci.setMinimumSize(new java.awt.Dimension(1550, 1000));
        panelSviPolasci.setPreferredSize(new java.awt.Dimension(1500, 1000));
        panelSviPolasci.setLayout(null);

        tabelaSviPolasci.setBackground(new java.awt.Color(153, 153, 153));
        tabelaSviPolasci.setForeground(new java.awt.Color(0, 0, 0));
        tabelaSviPolasci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaSviPolasci.setFocusable(false);
        tabelaSviPolasci.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaSviPolasci.setRowHeight(25);
        tabelaSviPolasci.setShowVerticalLines(false);
        tabelaSviPolasci.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaSviPolasci);

        panelSviPolasci.add(jScrollPane3);
        jScrollPane3.setBounds(15, 50, 1270, 530);

        btnObrisiPolazakIzTabeleSviPolasci.setBackground(new java.awt.Color(153, 153, 153));
        btnObrisiPolazakIzTabeleSviPolasci.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnObrisiPolazakIzTabeleSviPolasci.setForeground(new java.awt.Color(0, 0, 0));
        btnObrisiPolazakIzTabeleSviPolasci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_delete_64px.png"))); // NOI18N
        btnObrisiPolazakIzTabeleSviPolasci.setText("Obrisi polazak");
        btnObrisiPolazakIzTabeleSviPolasci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPolazakIzTabeleSviPolasciActionPerformed(evt);
            }
        });
        panelSviPolasci.add(btnObrisiPolazakIzTabeleSviPolasci);
        btnObrisiPolazakIzTabeleSviPolasci.setBounds(680, 590, 300, 50);

        btnUpdejtuj.setBackground(new java.awt.Color(153, 153, 153));
        btnUpdejtuj.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdejtuj.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdejtuj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_refresh_64px_1.png"))); // NOI18N
        btnUpdejtuj.setText("Izmeni polaske");
        btnUpdejtuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdejtujActionPerformed(evt);
            }
        });
        panelSviPolasci.add(btnUpdejtuj);
        btnUpdejtuj.setBounds(990, 590, 300, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_list_32px_1.png"))); // NOI18N
        jLabel4.setText("TABELA SVIH POLAZAKA:");
        panelSviPolasci.add(jLabel4);
        jLabel4.setBounds(15, 15, 300, 30);

        cmbSortiraj.setBackground(new java.awt.Color(153, 153, 153));
        cmbSortiraj.setForeground(new java.awt.Color(0, 0, 0));
        cmbSortiraj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "po datumu u opadajucem", "po datumu u rastucem ", "po liniji " }));
        cmbSortiraj.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSortirajItemStateChanged(evt);
            }
        });
        panelSviPolasci.add(cmbSortiraj);
        cmbSortiraj.setBounds(500, 15, 200, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/icons8_sort_32px_1.png"))); // NOI18N
        jLabel5.setText("Sortiraj:");
        panelSviPolasci.add(jLabel5);
        jLabel5.setBounds(400, 15, 90, 30);

        getContentPane().add(panelSviPolasci);
        panelSviPolasci.setBounds(0, 0, 1336, 768);

        jMenuBar1.setBackground(new java.awt.Color(187, 187, 187));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(620, 80));

        MeniLinijia.setBackground(new java.awt.Color(153, 153, 153));
        MeniLinijia.setForeground(new java.awt.Color(0, 0, 0));
        MeniLinijia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/meni_linija_80px.png"))); // NOI18N
        MeniLinijia.setText("Linija");
        MeniLinijia.setAlignmentX(1.0F);
        MeniLinijia.setAlignmentY(1.0F);
        MeniLinijia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MeniLinijia.setPreferredSize(new java.awt.Dimension(200, 50));
        MeniLinijia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeniLinijiaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MeniLinijia);

        MeniPolazak.setBackground(new java.awt.Color(153, 153, 153));
        MeniPolazak.setForeground(new java.awt.Color(0, 0, 0));
        MeniPolazak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/meni_oblak_voz_100.png"))); // NOI18N
        MeniPolazak.setText("Polazak");
        MeniPolazak.setAlignmentX(1.0F);
        MeniPolazak.setAlignmentY(1.0F);
        MeniPolazak.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MeniPolazak.setPreferredSize(new java.awt.Dimension(200, 30));
        MeniPolazak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeniPolazakMouseClicked(evt);
            }
        });
        jMenuBar1.add(MeniPolazak);

        MeniSviPolasci.setBackground(new java.awt.Color(102, 102, 102));
        MeniSviPolasci.setForeground(new java.awt.Color(0, 0, 0));
        MeniSviPolasci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/server/resources/icons/meni_lista_svi_polasci_100px.png"))); // NOI18N
        MeniSviPolasci.setText("Svi polasci");
        MeniSviPolasci.setAlignmentX(1.0F);
        MeniSviPolasci.setAlignmentY(1.0F);
        MeniSviPolasci.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MeniSviPolasci.setPreferredSize(new java.awt.Dimension(220, 50));
        MeniSviPolasci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeniSviPolasciMouseClicked(evt);
            }
        });
        jMenuBar1.add(MeniSviPolasci);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*DONE*/
    private void btnDodajMedjustanicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMedjustanicuActionPerformed
        int redniBroj = mtms.vratiSizeListe();
        Linija linija = (Linija) cmbLinije.getSelectedItem();
        Stanica s = (Stanica) cmbMedjustanica.getSelectedItem();
        MedjuStanica m = new MedjuStanica(s, linija, redniBroj);
        try {
            Kontroler.getInstance().unesiMedjustanicu(m);
            mtms.dodajUTabelu(m);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_btnDodajMedjustanicuActionPerformed

    /**/
    private void btnObrisiMedjustanicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiMedjustanicuActionPerformed
        int red = tabelaMedjustanica.getSelectedRow();
        if (red != -1) {
            MedjuStanica m = mtms.getList().get(red);

            Object[] options = {"Da", "Ne"};
            int n = JOptionPane.showOptionDialog(this,//parent container of JOptionPane
                    "Da li zaista zelite da obrisete medjustanicu:" + m.getStanica().getNaziv() + "?",
                    "PAZNJA",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,//do not use a custom Icon
                    options,//the titles of buttons
                    options[1]);//default button title
            if (n == 0) {
                try {
                    Kontroler.getInstance().obrisiMedjustanicu(m);
                    JOptionPane.showMessageDialog(this, "Uspesno ste obrisali medjustanicu iz baze!");
                    mtms.obrisi(red);
                    btnIzmeniRedosledMedjustanicaActionPerformed(evt);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.toString());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate da izaberete medjustanicu koju zelite da obrisete!");
            return;
        }
    }//GEN-LAST:event_btnObrisiMedjustanicuActionPerformed

//************************UNESI LINIJU***************************************//
    private void btnUnesiLinijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiLinijuActionPerformed
        Stanica pocetna = (Stanica) cmbPocetna.getSelectedItem();
        Stanica krajnja = (Stanica) cmbKrajnja.getSelectedItem();
        TipLinije tipLinije = (TipLinije) cmbTip.getSelectedItem();
        if (txtKilometraza.getText().isEmpty() || txtMinutaza.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti i minutazu i kilometrazu.");
            return;
        }
        int minutaza = Integer.parseInt(txtMinutaza.getText());
        double kilometraza = Double.parseDouble(txtKilometraza.getText());
        String naziv = pocetna.getNaziv() + " - " + krajnja.getNaziv() + " (" + tipLinije.getNaziv() + ")";
        lblNazivLinije.setText(naziv);
        Linija l = new Linija(-1, naziv, minutaza, kilometraza, pocetna, krajnja, tipLinije);
        try {
            Kontroler.getInstance().unesiLiniju(l);
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana linija: " + lblNazivLinije.getText() + "!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            lblNazivLinije.setText("");
        } finally {
            txtKilometraza.setText("");
            txtMinutaza.setText("");
        }
        dodajSveLinije();

    }//GEN-LAST:event_btnUnesiLinijuActionPerformed

    //************************TODO***************************************//
    private void btnIzmeniRedosledMedjustanicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniRedosledMedjustanicaActionPerformed
        ArrayList<MedjuStanica> list = mtms.vratiListu();
        if (!list.isEmpty()) {
            try {
                Kontroler.getInstance().izmeniSveMedjustanice(list);
                JOptionPane.showMessageDialog(this, "Uspesno sacuvano");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "GRESKA!\nNeuspesno sacuvano!");
            }
            promeniMedjustaniceZaLiniju();
        }

    }//GEN-LAST:event_btnIzmeniRedosledMedjustanicaActionPerformed

    //************************TO DO***************************************//
    private void cmbLinijeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLinijeItemStateChanged
        promeniMedjustaniceZaLiniju();
    }//GEN-LAST:event_cmbLinijeItemStateChanged

    //************************POSTAVI DANE KADA SE KLIKNE NA ODGOVARAJUCI MESEC U KOMBO BOX**************************************//
    private void cmbMeseciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMeseciItemStateChanged
        kalendar.promena();
    }//GEN-LAST:event_cmbMeseciItemStateChanged

    //************************POSTAVI DANE KADA SE KLIKNE NA ODGOVOARAJUCU GODINU U KOMBO BOX***************************************//
    private void cmbGodinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGodinaItemStateChanged
        kalendar.promena();
    }//GEN-LAST:event_cmbGodinaItemStateChanged

    //************************DODAJ POLAZAK***************************************//
    private void btnDodajPolazakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPolazakActionPerformed
        Linija l = (Linija) cmbLinijaPolazak.getSelectedItem();
        Voz v = (Voz) cmbVoz.getSelectedItem();
        int godina = (int) cmbGodina.getSelectedItem();
        int mesec = cmbMeseci.getSelectedIndex();
        int dan = (int) cmbDani.getSelectedItem();
        int sati = (Integer) spinerSati.getValue();
        int minuti = (Integer) spinerMinuti.getValue();
        int satiLinije = l.getMinutaza() / 60;
        int minutiLinije = l.getMinutaza() % 60;
        //u kalendaru meseci idu od 0 a u util datu idu od 1

        Calendar pocetniDatum = new GregorianCalendar(godina, mesec, dan, sati, minuti);
        Calendar krajnjiDatum = new GregorianCalendar(godina, mesec, dan, sati + satiLinije, minuti + minutiLinije);
        Date pocetni = pocetniDatum.getTime();
        Date krajnji = krajnjiDatum.getTime();
        Date danasnji = new Date();
        Calendar pocetniDatumaa2 = new GregorianCalendar(godina, mesec, dan, sati - 1, minuti);
        Date pocetniaa2 = pocetniDatumaa2.getTime();
        if (danasnji.after(pocetniaa2)) {
            JOptionPane.showMessageDialog(this, "Ne mozete napraviti polazak za datum koji je prosao!");
            return;
        }
        String datumPocetni = sdf.format(pocetni);
        String datumKrajnji = sdf.format(krajnji);
        lblDatumDolaska.setText(datumKrajnji);
        lblNazivPolaska.setText(l.getNaziv() + " [" + datumPocetni + " -> " + datumKrajnji + "]");
        String naziv = lblNazivPolaska.getText();
        Polazak polazak = new Polazak(-1, naziv, pocetni, krajnji, l, v);
        mtp.dodajUTabelu(polazak);
        boolean povratna = cboxPovratna.isSelected();
        ArrayList<Linija> listalinija = null;
        try {
            listalinija = Kontroler.getInstance().vratiMiSveLinije();
        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        Linija l2 = null;
        if (povratna) {
            for (Linija linija : listalinija) {
                if (linija.getTipLinije().getTipLinijeID() == l.getTipLinije().getTipLinijeID() && linija.getStanicaPocetna().getStanicaID() == l.getStanicaKrajnja().getStanicaID() && linija.getStanicaKrajnja().getStanicaID() == l.getStanicaPocetna().getStanicaID()) {
                    l2 = linija;
                    break;
                }
            }
        }
        Polazak povratni = null;
        if (povratna) {
            Calendar pocetniDatum2 = new GregorianCalendar(godina, mesec, dan, sati + satiLinije, minuti + minutiLinije + 30);
            Calendar krajnjiDatum2 = new GregorianCalendar(godina, mesec, dan, sati + satiLinije + satiLinije, minuti + minutiLinije + 30 + minutiLinije);
            Date pocetni2 = pocetniDatum2.getTime();
            Date krajnji2 = krajnjiDatum2.getTime();
            String datumPocetni2 = sdf.format(pocetni2);
            String datumKrajnji2 = sdf.format(krajnji2);
            String naziv2 = l2.getNaziv() + " [" + datumPocetni2 + " -> " + datumKrajnji2 + "]";
            povratni = new Polazak(-1, naziv2, pocetni2, krajnji2, l2, v);
            mtp.dodajUTabelu(povratni);
        }
        if (cmbBrojDanaZaPolazak.getSelectedIndex() != 0) {
            int broj = cmbBrojDanaZaPolazak.getSelectedIndex();
            int brojDana = 0;
            switch (broj) {
                case 1:
                    brojDana = 6;
                    break;
                case 2:
                    brojDana = 9;
                    break;
                case 3:
                    brojDana = 14;
                    break;
                default:
                    break;
            }
            for (int i = 1; i <= brojDana; i++) {
                Calendar pocetniDatumZ = new GregorianCalendar(godina, mesec, dan + i, sati, minuti);
                Calendar krajnjiDatumZ = new GregorianCalendar(godina, mesec, dan + i, sati + satiLinije, minuti + minutiLinije);
                Date pocetniZ = pocetniDatumZ.getTime();
                Date krajnjiZ = krajnjiDatumZ.getTime();
                String datumPocetniZ = sdf.format(pocetniZ);
                String datumKrajnjiZ = sdf.format(krajnjiZ);
                lblDatumDolaska.setText(datumKrajnji);
                String nazivZ = l.getNaziv() + " [" + datumPocetniZ + " -> " + datumKrajnjiZ + "]";
                Polazak polazakZ = new Polazak(-1, nazivZ, pocetniZ, krajnjiZ, l, v);
                mtp.dodajUTabelu(polazakZ);
                if (povratna) {
                    Calendar pocetniDatum2 = new GregorianCalendar(godina, mesec, dan + i, sati + satiLinije, minuti + minutiLinije + 30);
                    Calendar krajnjiDatum2 = new GregorianCalendar(godina, mesec, dan + i, sati + satiLinije + satiLinije, minuti + minutiLinije + 30 + minutiLinije);
                    Date pocetni2 = pocetniDatum2.getTime();
                    Date krajnji2 = krajnjiDatum2.getTime();
                    String datumPocetni2 = sdf.format(pocetni2);
                    String datumKrajnji2 = sdf.format(krajnji2);
                    String naziv2 = l2.getNaziv() + " [" + datumPocetni2 + " -> " + datumKrajnji2 + "]";
                    povratni = new Polazak(-1, naziv2, pocetni2, krajnji2, l2, v);
                    mtp.dodajUTabelu(povratni);
                }
            }
        }
    }//GEN-LAST:event_btnDodajPolazakActionPerformed

    private void btnZapamtiPolaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiPolaskeActionPerformed
        ArrayList<Polazak> list = mtp.vratiListu();
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lista je prazna!", "PAZNJA!", 2);
            return;
        }
        try {
            Kontroler.getInstance().unesiSvePolazke(list);
            JOptionPane.showMessageDialog(this, "Uspesno ste uneli listu polazaka!");
            mtp.obrisiListu();
            return;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesan unos liste polazaka!");
            return;
        }
    }//GEN-LAST:event_btnZapamtiPolaskeActionPerformed

    private void btnObrisiPolazakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPolazakActionPerformed
        int red = tabelaPolazaka.getSelectedRow();
        if (red != -1) {
            mtp.obrisi(red);
        }
    }//GEN-LAST:event_btnObrisiPolazakActionPerformed

    private void MeniLinijiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeniLinijiaMouseClicked
        pokreniPanelLinije();
    }//GEN-LAST:event_MeniLinijiaMouseClicked

    private void MeniPolazakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeniPolazakMouseClicked
        pokreniPanelPolazak();
    }//GEN-LAST:event_MeniPolazakMouseClicked

    private void btnObrisiLinijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiLinijuActionPerformed
        Linija l = (Linija) cmbLinije.getSelectedItem();
        Object[] options = {"Da", "Ne"};
        int n = JOptionPane.showOptionDialog(this,//parent container of JOptionPane
                "Da li zaista zelite da obrisete liniju: " + l.getNaziv() + "?",
                "PAZNJA",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,//do not use a custom Icon
                options,//the titles of buttons
                options[1]);//default button title

        if (n == 0) {
            try {
                Kontroler.getInstance().obrisiLiniju(l);
                JOptionPane.showMessageDialog(this, "Uspesno ste obrisali liniju: " + l.getNaziv() + ".");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno operacija brisanja linije: " + l.getNaziv() + ".");
            }
        }
        dodajSveLinije();
    }//GEN-LAST:event_btnObrisiLinijuActionPerformed

    private void MeniSviPolasciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeniSviPolasciMouseClicked
        pokreniPanelSviPolasci();
        dodajPolaske();
    }//GEN-LAST:event_MeniSviPolasciMouseClicked

    private void btnUnesiStanicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiStanicuActionPerformed
        String naziv = txtNazivStanice.getText();
        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popunini polje naziv!");
            return;
        }
        naziv = naziv.toUpperCase();
        Mesto mesto = (Mesto) cmbMestaZaStanice.getSelectedItem();
        Stanica s = new Stanica(-1, naziv, mesto);
        try {
            Kontroler.getInstance().unesiNovuStanicu(s);
            JOptionPane.showMessageDialog(this, "Uspesno ste uneli stanicu!");
            txtNazivStanice.setText("");
        } catch (Exception ex1) {
            JOptionPane.showMessageDialog(this, "Neuspesna operacija unosa stanice!");
            txtNazivStanice.setText("");
            Logger.getLogger(FormaLinija.class.getName()).log(Level.SEVERE, null, ex1);
        }

    }//GEN-LAST:event_btnUnesiStanicuActionPerformed

    private void cmbLinijaPolazakItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLinijaPolazakItemStateChanged
        Linija l = (Linija) cmbLinijaPolazak.getSelectedItem();
        if (l != null) {
            Linija linijaZaPretrazivanje = new Linija(-1, "", 0, 0, l.getStanicaKrajnja(), l.getStanicaPocetna(), l.getTipLinije());
            try {
                Linija linijaPovratna = Kontroler.getInstance().vratiLinijuNaOsnovuStanicaITipa(linijaZaPretrazivanje);
                cboxPovratna.setEnabled(true);
            } catch (Exception ex) {
                cboxPovratna.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmbLinijaPolazakItemStateChanged

    private void btnObrisiPolazakIzTabeleSviPolasciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPolazakIzTabeleSviPolasciActionPerformed
        int broj = tabelaSviPolasci.getSelectedRow();
        if (broj == -1) {
            JOptionPane.showMessageDialog(this, "Selektujte polazak koji zelite da obrisete!");
            return;
        } else {
            Polazak p = mtsp.getList().get(broj);
            Object[] options = {"Da", "Ne"};
            int n = JOptionPane.showOptionDialog(this,//parent container of JOptionPane
                    "Da li zaista zelite da obrisete polazak:" + p.getNaziv() + "?",
                    "PAZNJA",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,//do not use a custom Icon
                    options,//the titles of buttons
                    options[1]);//default button title
            if (n == 0) {
                try {
                    Kontroler.getInstance().obrisiPolazak(p);
                    JOptionPane.showMessageDialog(this, "Uspesno ste obrisali polazak!");
                    mtsp.obrisi(broj);
                    mtsp.fireTableDataChanged();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Ne mozete obrisati ovaj polazak!");
                }
            }
        }

    }//GEN-LAST:event_btnObrisiPolazakIzTabeleSviPolasciActionPerformed

    private void cmbSortirajItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSortirajItemStateChanged
        int broj = cmbSortiraj.getSelectedIndex();
        if (broj == -1) {
            return;
        }
        ArrayList<Polazak> polasci = mtsp.getList();
        Collections.sort(polasci, new Comparator<Polazak>() {
            @Override
            public int compare(Polazak o1, Polazak o2) {
                switch (broj) {
                    case 0:
                        if (o1.getDatumPolaska().after(o2.getDatumPolaska())) {
                            return -1;
                        }
                        return 1;
                    case 1:
                        if (o1.getDatumPolaska().before(o2.getDatumPolaska())) {
                            return -1;
                        }
                        return 1;
                    case 2:
                        if (o1.getLinija().getLinijaID() >= o2.getLinija().getLinijaID()) {
                            return -1;
                        }
                        return 1;
                }
                return 0;
            }
        });
        mtsp.setList(polasci);

    }//GEN-LAST:event_cmbSortirajItemStateChanged

    private void btnUpdejtujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdejtujActionPerformed
        ArrayList<Polazak> sviPolasci = mtsp.getList();
        ArrayList<Polazak> polasciZaMenjanje = new ArrayList<>();
        for (Polazak polazak : sviPolasci) {
            if (polazak.getNapomena() == null || !polazak.getNapomena().isEmpty()) {
                polasciZaMenjanje.add(polazak);
            }
        }
        if (polasciZaMenjanje.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nema polazaka za izmenu!");
            return;
        }
        boolean uspesno = false;
        try {
            Kontroler.getInstance().updejtujMiPolaske(polasciZaMenjanje);
            uspesno = true;

        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "USPESNA IZMENA");

        } else {
            JOptionPane.showMessageDialog(this, "NEUSPESNA IZMENA");

        }

    }//GEN-LAST:event_btnUpdejtujActionPerformed

    private void btnObrisiListuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiListuActionPerformed
        mtp.obrisiListu();
    }//GEN-LAST:event_btnObrisiListuActionPerformed

    private void lblDarkModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDarkModeMouseClicked
        ukljuciDarkMode();
    }//GEN-LAST:event_lblDarkModeMouseClicked

    private void lblWhiteModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhiteModeMouseClicked
        iskljuciDarkMode();
    }//GEN-LAST:event_lblWhiteModeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaLinija.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaLinija.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaLinija.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaLinija.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaLinija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MeniLinijia;
    private javax.swing.JMenu MeniPolazak;
    private javax.swing.JMenu MeniSviPolasci;
    private javax.swing.JButton btnDodajMedjustanicu;
    private javax.swing.JButton btnDodajPolazak;
    private javax.swing.JButton btnIzmeniRedosledMedjustanica;
    private javax.swing.JLabel btnLinija;
    private javax.swing.JButton btnObrisiLiniju;
    private javax.swing.JButton btnObrisiListu;
    private javax.swing.JButton btnObrisiMedjustanicu;
    private javax.swing.JButton btnObrisiPolazak;
    private javax.swing.JButton btnObrisiPolazakIzTabeleSviPolasci;
    private javax.swing.JButton btnUnesiLiniju;
    private javax.swing.JButton btnUnesiStanicu;
    private javax.swing.JButton btnUpdejtuj;
    private javax.swing.JButton btnZapamtiPolaske;
    private javax.swing.JCheckBox cboxPovratna;
    private javax.swing.JComboBox<String> cmbBrojDanaZaPolazak;
    private javax.swing.JComboBox cmbDani;
    private javax.swing.JComboBox cmbGodina;
    private javax.swing.JComboBox cmbKrajnja;
    private javax.swing.JComboBox cmbLinijaPolazak;
    private javax.swing.JComboBox cmbLinije;
    private javax.swing.JComboBox cmbMedjustanica;
    private javax.swing.JComboBox<String> cmbMeseci;
    private javax.swing.JComboBox cmbMestaZaStanice;
    private javax.swing.JComboBox cmbPocetna;
    private javax.swing.JComboBox<String> cmbSortiraj;
    private javax.swing.JComboBox cmbTip;
    private javax.swing.JComboBox cmbVoz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDarkMode;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatum1;
    private javax.swing.JLabel lblDatumDolaska;
    private javax.swing.JLabel lblKm;
    private javax.swing.JLabel lblKm1;
    private javax.swing.JLabel lblKranja;
    private javax.swing.JLabel lblListaPolazaka;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblNaziv2;
    private javax.swing.JLabel lblNaziv3;
    private javax.swing.JLabel lblNaziv4;
    private javax.swing.JLabel lblNazivFrejma;
    private javax.swing.JLabel lblNazivFrejma1;
    private javax.swing.JLabel lblNazivFrejma2;
    private javax.swing.JLabel lblNazivLinije;
    private javax.swing.JLabel lblNazivLinijeKodTabele;
    private javax.swing.JLabel lblNazivPolaska;
    private javax.swing.JLabel lblSat;
    private javax.swing.JLabel lblTip;
    private javax.swing.JLabel lblVoz;
    private javax.swing.JLabel lblWhiteMode;
    private javax.swing.JLabel lblpocetna;
    private javax.swing.JLabel lblpocetna1;
    private javax.swing.JPanel panelLinija;
    private javax.swing.JPanel panelPolazak;
    private javax.swing.JPanel panelSviPolasci;
    private javax.swing.JSpinner spinerMinuti;
    private javax.swing.JSpinner spinerSati;
    private javax.swing.JTable tabelaMedjustanica;
    private javax.swing.JTable tabelaPolazaka;
    private javax.swing.JTable tabelaSviPolasci;
    private javax.swing.JTextField txtKilometraza;
    private javax.swing.JTextField txtMinutaza;
    private javax.swing.JTextField txtNazivStanice;
    // End of variables declaration//GEN-END:variables

    private void centrirajFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        setLocationRelativeTo(null);
        this.setSize(1336, 768);
    }

    private void pokreniServer() {
        PokreniServerNit psn = new PokreniServerNit();
        psn.start();
    }

    private void dodajStanice() {
        cmbPocetna.removeAllItems();
        cmbKrajnja.removeAllItems();
        cmbMedjustanica.removeAllItems();
        ArrayList<Stanica> list = null;
        try {
            list = Kontroler.getInstance().vratiMiSveStanice();

        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (Stanica stanica : list) {
            cmbPocetna.addItem(stanica);
            cmbKrajnja.addItem(stanica);
            cmbMedjustanica.addItem(stanica);
        }
    }

    private void dodajMesta() {
        ArrayList<Mesto> listaMesta = null;
        try {
            listaMesta = Kontroler.getInstance().vratiListuMesta();
        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbMestaZaStanice.removeAllItems();
        for (Mesto mesto : listaMesta) {
            cmbMestaZaStanice.addItem(mesto);
        }
    }

    private void dodajTipoveLinija() {
        cmbTip.removeAllItems();
        ArrayList<TipLinije> list = null;
        try {
            list = Kontroler.getInstance().vratiMiSveTipoveLinije();

        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (TipLinije tipLinije : list) {
            cmbTip.addItem(tipLinije);
        }
    }

    private void dodajSveLinije() {
        cmbLinije.removeAllItems();
        cmbLinijaPolazak.removeAllItems();
        ArrayList<Linija> list = null;
        try {
            list = Kontroler.getInstance().vratiMiSveLinije();
            for (Linija linija : list) {
                cmbLinije.addItem(linija);
                cmbLinijaPolazak.addItem(linija);

            }
        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void dodajVozove() {
        cmbVoz.removeAllItems();
        ArrayList<Voz> vozovi = null;
        try {
            vozovi = Kontroler.getInstance().vratiMiSveVozove();

        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (Voz voz : vozovi) {
            cmbVoz.addItem(voz);
        }
    }

    private void dodajPolaske() {
        tabelaSviPolasci.setModel(mtsp);
        ArrayList<Polazak> polasci = null;
        try {
            polasci = Kontroler.getInstance().vratiListuPolazaka();
        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        mtsp.setList(polasci);
        mtsp.fireTableDataChanged();
    }

    private void ucitajSveIzBaze() {
        dodajMesta();
        dodajVozove();
        dodajTipoveLinija();
        dodajStanice();
        dodajSveLinije();
        dodajPolaske();
    }

    private void urediTabeluPolazaka() {
        tabelaPolazaka.setModel(mtp);
        tabelaPolazaka.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaPolazaka.getColumnModel().getColumn(0).setResizable(false);
        tabelaPolazaka.getColumnModel().getColumn(1).setResizable(false);
        tabelaPolazaka.getColumnModel().getColumn(2).setResizable(false);
        tabelaPolazaka.getColumnModel().getColumn(3).setResizable(false);
        tabelaPolazaka.getColumnModel().getColumn(4).setResizable(false);
        tabelaPolazaka.getColumnModel().getColumn(0).setWidth(25);
        tabelaPolazaka.getColumnModel().getColumn(1).setMaxWidth(519);
        tabelaPolazaka.getColumnModel().getColumn(1).setMinWidth(519);
        tabelaPolazaka.getColumnModel().getColumn(2).setMaxWidth(120);
        tabelaPolazaka.getColumnModel().getColumn(2).setMinWidth(120);
        tabelaPolazaka.getColumnModel().getColumn(3).setMaxWidth(120);
        tabelaPolazaka.getColumnModel().getColumn(3).setMinWidth(120);
        tabelaPolazaka.getColumnModel().getColumn(4).setMaxWidth(70);
        tabelaPolazaka.getColumnModel().getColumn(4).setMinWidth(70);
        tabelaPolazaka.getColumnModel().getColumn(5).setMaxWidth(250);
        tabelaPolazaka.getColumnModel().getColumn(5).setMinWidth(250);
    }

    private void urediTabeluSviPolasci() {
        tabelaSviPolasci.setModel(mtsp);
        tabelaSviPolasci.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaSviPolasci.getColumnModel().getColumn(0).setResizable(false);
        tabelaSviPolasci.getColumnModel().getColumn(1).setResizable(false);
        tabelaSviPolasci.getColumnModel().getColumn(2).setResizable(false);
        tabelaSviPolasci.getColumnModel().getColumn(3).setResizable(false);
        tabelaSviPolasci.getColumnModel().getColumn(4).setResizable(false);
        tabelaSviPolasci.getColumnModel().getColumn(0).setWidth(25);
        tabelaSviPolasci.getColumnModel().getColumn(1).setMaxWidth(400);
        tabelaSviPolasci.getColumnModel().getColumn(1).setMinWidth(400);
        tabelaSviPolasci.getColumnModel().getColumn(2).setMaxWidth(200);
        tabelaSviPolasci.getColumnModel().getColumn(2).setMinWidth(200);
        tabelaSviPolasci.getColumnModel().getColumn(3).setMaxWidth(200);
        tabelaSviPolasci.getColumnModel().getColumn(3).setMinWidth(200);
        tabelaSviPolasci.getColumnModel().getColumn(4).setMaxWidth(115);
        tabelaSviPolasci.getColumnModel().getColumn(4).setMinWidth(115);
        tabelaSviPolasci.getColumnModel().getColumn(5).setMaxWidth(250);
        tabelaSviPolasci.getColumnModel().getColumn(5).setMinWidth(250);

    }

    private void urediTabeluMedjuStanica() {
        tabelaMedjustanica.setModel(mtms);
        tabelaMedjustanica.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaMedjustanica.getColumnModel().getColumn(0).setResizable(false);
        tabelaMedjustanica.getColumnModel().getColumn(1).setResizable(false);

        tabelaMedjustanica.getColumnModel().getColumn(0).setWidth(50);
        tabelaMedjustanica.getColumnModel().getColumn(1).setMinWidth(519);
        tabelaMedjustanica.getColumnModel().getColumn(1).setMaxWidth(519);

    }

    private void promeniMedjustaniceZaLiniju() {
        mtms.izbrisiListu();
        Linija l = (Linija) cmbLinije.getSelectedItem();
        if (l == null) {
            return;
        }
        lblNazivLinijeKodTabele.setText("Lista medjustanica za liniju: " + l.getNaziv());
        ArrayList<MedjuStanica> lista = null;
        try {
            lista = Kontroler.getInstance().vratiMiSveMedjustaniceZaLiniju(new MedjuStanica(null, l, -1));
        } catch (Exception ex) {
            Logger.getLogger(FormaLinija.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        mtms.setList(lista);
    }

    private void ukljuciDarkMode() {
        lblWhiteMode.setVisible(true);
        lblDarkMode.setVisible(false);
        tema.blackTheme();
    }

    private void iskljuciDarkMode() {
        lblWhiteMode.setVisible(false);
        lblDarkMode.setVisible(true);
        tema.whiteTheme();
    }

    private void pokreniPanelLinije() {
        panelLinija.setVisible(true);
        panelPolazak.setVisible(false);
        panelSviPolasci.setVisible(false);
    }

    private void pokreniPanelPolazak() {
        panelLinija.setVisible(false);
        panelPolazak.setVisible(true);
        panelSviPolasci.setVisible(false);
    }

    private void pokreniPanelSviPolasci() {
        panelLinija.setVisible(false);
        panelPolazak.setVisible(false);
        panelSviPolasci.setVisible(true);
    }

}
